accounts/urls.py
from django.urls import path
from django.views.generic import FormView

from accounts.api_endpoints import (
    CartItemListAPIView,
    CartItemCreateAPIView,
    CartItemUpdateAPIView,
    CartItemDeleteAPIView,
    SessionLoginAPIView,
    SessionLogoutAPIView,
    ProfileUpdateAPIView,
    ProfileDeleteAPIView,
    RequestPasswordResetView,
    PasswordResetConfirmAPIView,
    VerifyEmailView,
    RegisterView, SaveProductAPIView, SavedProductListAPIView
)
from products.api_endpoints import UserReviewsListAPIView, UserCommentsListAPIView
from .views import *
from .template_views import *

urlpatterns = [
    path('login/', SessionLoginAPIView.as_view(), name="login-session"),
    path('logout/', SessionLogoutAPIView.as_view(), name="logout-session"),
    path('cart-items/', CartItemListAPIView.as_view(), name='cart-items'),
    path('cart/cart_items/create/', CartItemCreateAPIView.as_view(), name='cart-item-create'),
    path('cart/cart_items/delete/<int:pk>/', CartItemDeleteAPIView.as_view(), name='cart-item-delete'),
    path('cart/cart_items/update/<int:pk>/', CartItemUpdateAPIView.as_view(), name='cart-item-update'),

    # Profile
    path('profile/update/', ProfileUpdateAPIView.as_view(), name='profile-update'),
    path('profile/delete/<int:pk>/', ProfileDeleteAPIView.as_view(), name='profile-update'),

    path('password-reset/', RequestPasswordResetView.as_view(), name="password-reset"),
    path('password-reset/confirm/', PasswordResetConfirmAPIView.as_view(), name="password-reset-confirm"),
    path('verify-email/', VerifyEmailView.as_view(), name="verify-email"),
    path('register/', RegisterView.as_view(), name="register"),

    # Reviews, Comments
    path('profile/reviews/', UserReviewsListAPIView.as_view(), name='user-reviews'),
    path('profile/comments/', UserCommentsListAPIView.as_view(), name='user-comments'),

    # Saved Products
    path('product/save-unsave', SaveProductAPIView.as_view(), name='save-unsave-product'),

    #template_views
    path("template/register/", RegisterTemplateView.as_view(), name="register-template"),
    path("template/login/", LoginTemplateView.as_view(), name="login-template"),
    path("template/profile/", ProfileTemplateView.as_view(), name="profile-template"),

    # Saved Products
    path('saved_products/', SavedProductListAPIView.as_view(), name='saved-products'),
    path('saved_products/create/', SaveProductAPIView.as_view(), name='saved-product-create'),
]

common/urls.py
from django.urls import path

from .views import HomePageView, ContactPageView, ShopDetailsView, ShopCart, ShopGridView, CheckoutPageView, BlogPageView, SavedProductsPageView
from .apis import *


app_name = 'common'

urlpatterns = [

    # templates
    path('index/', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('shop-details/', ShopDetailsView.as_view(), name='shop-details'),
    path('shop-cart/', ShopCart.as_view(), name='shop-cart'),
    path('shop-grid/', ShopGridView.as_view(), name='shop-grid'),
    path('checkout/', CheckoutPageView.as_view(), name='checkout'),
    path('blog/', BlogPageView.as_view(), name='blog'),
    path('saved_products/', SavedProductsPageView.as_view(), name='saved-products'),

    # Media CRUD
    path('mediafiles/list/', MediaFileGetAPIView.as_view(), name='mediafile-list'),
    path('mediafiles/create/', MediaFileCreateAPIView.as_view(), name='mediafile-create'),
    path('mediafiles/delete/<int:id>/', MediaFileDeleteAPIView.as_view(), name='mediafile-delete'),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="My API",
      default_version='v1',
      description="Test API for authentication methods",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="admin@example.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
   authentication_classes=[],
)


urlpatterns = [
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('common/', include('common.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls')),
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('i18n/', include('django.conf.urls.i18n')),
]

static_media_urls = (
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    +
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

urlpatterns += static_media_urls


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls')),
    ]

accounts/api_endpoints/Profile/PasswordReset/views.py
from rest_framework.views import APIView
from rest_framework import status, permissions
from rest_framework.response import Response

from drf_yasg.utils import swagger_auto_schema

from .serializer import PasswordResetRequestSerializer, PasswordResetConfirmSerializer
from accounts.api_endpoints.email_send import send_email


class RequestPasswordResetView(APIView):
    @swagger_auto_schema(
        request_body=PasswordResetRequestSerializer,
    )
    def post(self, request):
        serializer = PasswordResetRequestSerializer(data=request.data, context={
            'send_email': send_email
        })
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({'detail': 'Password reset email sent'}, status=status.HTTP_200_OK)


class PasswordResetConfirmAPIView(APIView):
    permission_classes = []
    @swagger_auto_schema(
        request_body=PasswordResetConfirmSerializer,
    )
    def post(self, request):
        serializer = PasswordResetConfirmSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"detail": "Password has been reset successfully."}, status=200)

accounts/api_endpoints/Profile/ProfileDelete/views.py
from rest_framework.generics import DestroyAPIView, GenericAPIView
from rest_framework import permissions

from accounts.models import User


class ProfileDeleteAPIView(DestroyAPIView):
    queryset = User.objects.all()
    permission_classes = [permissions.IsAuthenticated]

    def perform_destroy(self, instance):
        instance.is_active = False
        instance.save()

accounts/api_endpoints/Profile/ProfileUpdate/views.py
from rest_framework import permissions, parsers
from rest_framework.generics import UpdateAPIView, GenericAPIView

from accounts.models import User
from .serializer import ProfileUpdateSerializer


class ProfileUpdateAPIView(UpdateAPIView):
    queryset = User.objects.all()
    serializer_class = ProfileUpdateSerializer
    permission_classes = [permissions.IsAuthenticated]
    parser_classes = [parsers.MultiPartParser, parsers.FormParser]

    def get_object(self):
        return User.objects.filter(id=self.request.user.id).first()

orders/apis/CheckOut/views.py
from rest_framework.generics import CreateAPIView
from rest_framework import permissions

from .serializer import CheckOutSerializer


class CheckOutAPIView(CreateAPIView):
    serializer_class = CheckOutSerializer
    permission_classes = [permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        return super().create(request, *args, **kwargs)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/font-awesome.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/elegant-icons.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/nice-select.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/jquery-ui.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/owl.carousel.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/slicknav.min.css" %}' type="text/css">
    <link rel="stylesheet" href='{% static "css/style.css" %}' type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="{% url "common:home" %}"><img src="{% static "img/logo.png" %}" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="{% url 'common:saved-products' %}"><i class="fa fa-heart"></i> <span>1</span></a></li>
                <li><a href="{% url "common:shop-cart" %}"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
            </ul>
            <div class="header__cart__price">item: <span>$150.00</span></div>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__language">
                <img src="{% static "img/language.png" %}" alt="">
                <div>English</div>
                <span class="arrow_carrot-down"></span>
                <ul>
                    <li><a href="#">Spanish</a></li>
                    <li><a href="#">English</a></li>
                </ul>
            </div>

            {% if not is_user.authenticated %}
            <div class="header__top__right__auth">
                <a href="{% url 'accounts:login-template' %}"><i class="fa fa-user"></i>Login</a>
            </div>
{#            <div class="header__top__left__auth">#}
{#                <a href="{% url 'accounts:register-template' %}"><i class="fa fa-user"></i>Register</a>#}
{#            </div>#}
            {% endif %}

        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a href="{% url 'common:home' %}">Home</a></li>
                <li><a href="{% url "common:shop-grid" %}">Shop</a></li>
                <li><a href="#">Pages</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="{% url "common:shop-details" %}">Shop Details</a></li>
                        <li><a href="{% url "common:shop-cart" %}">Shoping Cart</a></li>
                        <li><a href="{% url "common:checkout" %}">Check Out</a></li>
                        <li><a href="{% url "common:blog" %}">Blog Details</a></li>
                    </ul>
                </li>
                <li><a href="{% url "common:blog" %}">Blog</a></li>
                <li><a href="{% url "common:contact" %}">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
                <li>Free Shipping for all Order of $99</li>
            </ul>
        </div>
    </div>
    <!-- Humberger End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
                                <li>Free Shipping for all Order of $99</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p"></i></a>
                            </div>
                            <div class="header__top__right__language">
                                <img src="{% static "img/language.png" %}" alt="">
                                <div>English</div>
                                <span class="arrow_carrot-down"></span>
                                <ul>
                                    <li><a href="#">Spanish</a></li>
                                    <li><a href="#">English</a></li>
                                </ul>
                            </div>
                            <div class="header__top__right__auth">
                                <a href="{% url "accounts:login-template" %}"><i class="fa fa-user"></i> Login</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="{% url "common:home" %}"><img src="{% static "img/logo.png" %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="{% url "common:home" %}">Home</a></li>
                            <li><a href="{% url "common:shop-grid" %}">Shop</a></li>
                            <li><a href="{% url "common:shop-details" %}">Pages</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="{% url "common:shop-details" %}">Shop Details</a></li>
                                    <li><a href="{% url "common:shop-cart" %}">Shoping Cart</a></li>
                                    <li><a href="{% url "common:checkout" %}">Check Out</a></li>
                                    <li><a href="{% url "common:blog" %}">Blog Details</a></li>
                                </ul>
                            </li>
                            <li><a href="{% url "common:shop-grid" %}">Blog</a></li>
                            <li><a href={% url 'common:contact' %}>Contact</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">

                    {% if is_user_authenticated %}
                    <div class="header__cart">
                        <ul>
                            <li><a href="{% url 'common:saved-products' %}"><i class="fa fa-heart"></i> <span>0</span></a></li>
                            <li><a href="{% url "common:shop-cart" %}"><i class="fa fa-shopping-bag"></i> <span>{{ user_art_items_count }}</span></a></li>
                        </ul>
                        <div class="header__cart__price">item: <span>{{ cart_total_amount }}</span></div>
                    </div>
                    {% endif %}

                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

{% block content %}

{% endblock content %}

<!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="{% url "common:home" %}"><img src="{% static "img/logo.png" %}" alt=""></a>
                        </div>
                        <ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: hello@colorlib.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
                        <div class="footer__copyright__payment"><img src="img/payment-item.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    <script src='{%static "js/jquery.nice-select.min.js" %}'></script>
    <script src='{% static "js/jquery-ui.min.js" %}'></script>
    <script src='{% static "js/jquery.slicknav.js" %}'></script>
    <script src='{% static "js/mixitup.min.js" %}'></script>
    <script src='{% static "js/owl.carousel.min.js" %}'></script>
    <script src='{% static "js/main.js" %}'></script>



</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Contact Us</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url "common:home" %}">Home</a>
                            <span>Contact Us</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_phone"></span>
                        <h4>Phone</h4>
                        <p>+01-3-8888-6868</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_pin_alt"></span>
                        <h4>Address</h4>
                        <p>60-49 Road 11378 New York</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_clock_alt"></span>
                        <h4>Open time</h4>
                        <p>10:00 am to 23:00 pm</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 text-center">
                    <div class="contact__widget">
                        <span class="icon_mail_alt"></span>
                        <h4>Email</h4>
                        <p>hello@colorlib.com</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

    <!-- Map Begin -->
    <div class="map">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d49116.39176087041!2d-86.41867791216099!3d39.69977417971648!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x886ca48c841038a1%3A0x70cfba96bf847f0!2sPlainfield%2C%20IN%2C%20USA!5e0!3m2!1sen!2sbd!4v1586106673811!5m2!1sen!2sbd"
            height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        <div class="map-inside">
            <i class="icon_pin"></i>
            <div class="inside-widget">
                <h4>New York</h4>
                <ul>
                    <li>Phone: +12-345-6789</li>
                    <li>Add: 16 Creek Ave. Farmingdale, NY</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Map End -->

    <!-- Contact Form Begin -->
    <div class="contact-form spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="contact__form__title">
                        <h2>Leave Message</h2>
                    </div>
                </div>
            </div>
                        <form method="post">
                          {% csrf_token %}
                          {{ form.as_p }}
                          <button type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Contact Form End -->

{% endblock content %}

templates/login.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}ECommerce | Login{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form action="{% url 'accounts:login-session' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password|as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </form>
            <br>
        </div>
    </div>
</div>

{% endblock content %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/register.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}VooCommerce | Register{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form action="{% url 'register' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="col">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="form-group">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password1|as_crispy_field }}
                </div>
                <div class="form-group">
                    {{ form.password2|as_crispy_field }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Register</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/reset_password_email.html
<html>
<body>
    <p>Hello the owner of {{ email }},</p>
    <p>Click the link below to reset your password:</p>
    <p>{{intro_text}}</p>
    <p>
        <a href="{{ frontend_url }}/reset-password?token={{ token }}">
            Reset Password
            {{subject}}
        </a>
    </p>
    {% if password %}
    <p>
        Your new password is: <b>{{password}}</b>. Please reset your password after logging into your account.
    </p>
    {% endif %}
    <p>This link will expire in 1 hour.</p>
</body>
</html>

templates/saved_products_temolate.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Saved Products</h2>
                        <div class="breadcrumb__option">
                            <a href="{% url "common:home" %}">Home</a>
                            <span>Saved Products</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Saved Products Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shoping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th class="shoping__product">Products</th>
                                    <th>Price</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>

                            {% for product in products %}
                                <tr>
                                    <td class="shoping__cart__item">
                                        <img height=50 width=50 src="{% if product.images %}{{ product.images.url}}{% else %}{% static "img/default-image.jpg" %}{% endif %}" alt="">
                                        <h5>{{ product.name }}</h5>
                                    </td>
                                    <td class="shoping__cart__price">
                                        ${{ product.price }}
                                    </td>
                                    <td class="shoping__cart__item__close">
                                        <span class="icon_close"></span>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <!-- Shoping Cart Section End -->

{% endblock content %}

templates/send_verify_email.html
<!DOCTYPE html>
<html>
<body>
    <p>Hello the owner of {{ email }},</p>
    <p>Click the link below to verify your password:</p>
    <p>
        <a href="{{ verify_url }}/verify-email/?token={{ token }}">
            Verify Account
        </a>
    </p>
    <p>This link will expire in 1 hour.</p>
</body>
</html>